// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  introSidebar: [{type: 'autogenerated', dirName: 'theory/introduction'}],
  toolsSidebar: [{type: 'autogenerated', dirName: 'theory/tools'}],
  sensorSidebar: [{type: 'autogenerated', dirName: 'theory/sensor'}],
  objectSidebar: [{type: 'autogenerated', dirName: 'theory/object'}],
  vehicleSidebar: [{type: 'autogenerated', dirName: 'theory/vehicle'}],
  connectedSidebar: [{type: 'autogenerated', dirName: 'theory/connected'}],
  taskSidebar: [{type: 'autogenerated', dirName: 'task'}],
  cppSidebar: [{type: 'autogenerated', dirName: 'cpp'}],
  pySidebar: [{type: 'autogenerated', dirName: 'python'}],
  rosSidebar: [{type: 'autogenerated', dirName: 'ros'}],
  ros2Sidebar: [{type: 'autogenerated', dirName: 'ros2'}],
};

export default sidebars;
